nodes:
    cfg01.mcp11-ovs-dpdk.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    cid01.mcp11-ovs-dpdk.local:
      reclass_storage_name: cicd_control_node01
      roles:
      - infra_kvm
      - cicd_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    cid02.mcp11-ovs-dpdk.local:
      reclass_storage_name: cicd_control_node02
      roles:
      - infra_kvm
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    cid03.mcp11-ovs-dpdk.local:
      reclass_storage_name: cicd_control_node03
      roles:
      - infra_kvm
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    ctl01.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - openstack_control_leader
      - openstack_database_leader
      - openstack_message_queue
      - features_designate_database
      - features_designate
      - features_designate_keystone
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    ctl02.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - features_designate_database
      - features_designate
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    ctl03.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - features_designate_database
      - features_designate
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    prx01.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - features_designate_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    prx02.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_proxy_node02
      roles:
      - openstack_proxy
      - features_designate_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mon01.mcp11-ovs-dpdk.local:
      reclass_storage_name: stacklight_server_node01
      roles:
      - stacklightv2_server_leader
      - stacklight_telemetry_leader
      - stacklight_log_leader_v2
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mon02.mcp11-ovs-dpdk.local:
      reclass_storage_name: stacklight_server_node02
      roles:
      - stacklightv2_server
      - stacklight_telemetry
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mon03.mcp11-ovs-dpdk.local:
      reclass_storage_name: stacklight_server_node03
      roles:
      - stacklightv2_server
      - stacklight_telemetry
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    # Generator-based computes. For compatibility only
    cmp<<count>>.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens5:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens6:
          role: bond1_ab_ovs_floating

    gtw01.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      classes:
      - system.linux.system.repo.mcp.apt_mirantis.docker
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens5:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens6:
          role: bond1_ab_ovs_floating

    gtw02.mcp11-ovs-dpdk.local:
      reclass_storage_name: openstack_gateway_node02
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens5:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens6:
          role: bond1_ab_ovs_floating
