nodes:
    cfg01:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      - features_runtest
      classes:
      - environment.cookied-small-mcp-ironic.override_ntp_virtual
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_static_ctl

    ctl01:
      reclass_storage_name: openstack_control_node01
      roles:
      - infra_kvm
      - openstack_control_leader
      - openstack_database_leader
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl02:
      reclass_storage_name: openstack_control_node02
      roles:
      - infra_kvm
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    ctl03:
      reclass_storage_name: openstack_control_node03
      roles:
      - infra_kvm
      - openstack_control
      - openstack_database
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    prx01:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy  # another VIP interface used
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: single_external
          external_address: 172.17.16.121
          external_network_netmask: 255.255.255.0

    gtw01:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - linux_system_codename_xenial
      classes:
      - system.linux.system.repo.mcp.apt_mirantis.docker
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating
        ens7:
          role: single_ovs_br_baremetal

    bmt01:
      reclass_storage_name: openstack_baremetal_node01
      roles:
      - openstack_baremetal
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens7:
          role: single_baremetal

    cmp<<count>>:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - features_lvm_backend_volume_vdb
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl
        ens5:
          role: bond0_ab_ovs_vxlan_mesh
        ens6:
          role: bond1_ab_ovs_floating
