nodes:
    cfg01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    kvm01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: infra_kvm_node01
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    kvm02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: infra_kvm_node02
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    kvm03.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: infra_kvm_node03
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    cid01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: cicd_control_node01
      roles:
      - cicd_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    cid02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: cicd_control_node02
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    cid03.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: cicd_control_node03
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    ctl01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - openstack_control_leader
      - features_designate
      - features_designate_keystone
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    ctl02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - openstack_control
      - features_designate
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    ctl03.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - openstack_control
      - features_designate
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    dbs01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_database_node01
      roles:
      - openstack_database_leader
      - features_designate_database
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    dbs02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_database_node02
      roles:
      - openstack_database
      - features_designate_database
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    dbs03.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_database_node03
      roles:
      - openstack_database
      - features_designate_database
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    msg01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_message_queue_node01
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    msg02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_message_queue_node02
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    msg03.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_message_queue_node03
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    prx01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - features_designate_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    prx02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_proxy_node02
      roles:
      - openstack_proxy
      - features_designate_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mon01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_server_node01
      roles:
      - stacklightv2_server_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mon02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_server_node02
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mon03.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_server_node03
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mtr01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_telemetry_node01
      roles:
      - stacklight_telemetry_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mtr02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_telemetry_node02
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mtr03.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_telemetry_node03
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    log01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_log_node01
      roles:
      - stacklight_log_leader_v2
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    log02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_log_node02
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    log03.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_log_node03
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    # Generator-based computes. For compatibility only
    cmp<<count>>.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens5:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens6:
          role: bond1_ab_ovs_floating

    gtw01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      classes:
      - system.linux.system.repo.mcp.apt_mirantis.docker
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens5:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens6:
          role: bond1_ab_ovs_floating

    gtw02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_gateway_node02
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens5:
          role: bond0_ab_ovs_vxlan_ctl_mesh
        ens6:
          role: bond1_ab_ovs_floating
