nodes:
    cfg01.cookied-bm-dvr-vxlan.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
#        ens4:
#          role: single_vlan_ctl

    # Physical nodes
    kvm01.cookied-bm-dvr-vxlan.local:
      reclass_storage_name: infra_kvm_node01
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp2s0f0:
          role: single_mgm_dhcp
        enp2s0f1:
          role: bond0_ab_ovs_vlan_ctl

    kvm02.cookied-bm-dvr-vxlan.local:
      reclass_storage_name: infra_kvm_node02
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp2s0f0:
          role: single_mgm_dhcp
        enp2s0f1:
          role: bond0_ab_ovs_vlan_ctl

    kvm03.cookied-bm-dvr-vxlan.local:
      reclass_storage_name: infra_kvm_node03
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        eno1:
          role: single_mgm_dhcp
        eno2:
          role: bond0_ab_ovs_vlan_ctl

    cmp001.cookied-bm-dvr-vxlan.local:
      reclass_storage_name: openstack_compute_node01
      roles:
      - openstack_compute
      - linux_system_codename_xenial
      interfaces:
        enp3s0f0:
          role: single_dhcp
        enp3s0f1:
          role: bond0_ab_ovs_vxlan_ctl_mesh
          single_address: ${_param:openstack_compute_node01_control_address}
          tenant_address: ${_param:openstack_compute_node01_tenant_address}
        enp5s0f0:
          role: bond0_ab_ovs_vxlan_ctl_mesh
# Which of enp5s0f1. enp5s0f2, enp5s0f3 is for floating?
#        ens6:
#          role: bond1_ab_ovs_floating

    cmp002.cookied-bm-dvr-vxlan.local:
      reclass_storage_name: openstack_compute_node02
      roles:
      - openstack_compute
      - linux_system_codename_xenial
      interfaces:
        eno1:
          role: single_dhcp
        enp5s0f0:
          role: bond0_ab_ovs_vxlan_ctl_mesh
          single_address: ${_param:openstack_compute_node02_control_address}
          tenant_address: ${_param:openstack_compute_node02_tenant_address}
        enp5s0f2:
          role: bond0_ab_ovs_vxlan_ctl_mesh
# Which of eno2, enp5s0f1, enp5s0f3 is for floating?
#        ens6:
#          role: bond1_ab_ovs_floating

    gtw01.cookied-bm-dvr-vxlan.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        enp3s0f0:
          role: single_dhcp
        enp3s0f1:
          role: bond0_ab_dvr_vxlan_ctl_mesh_floating

    #gtw02.cookied-bm-dvr-vxlan.local:
    #  reclass_storage_name: openstack_gateway_node02
    #  roles:
    #  - openstack_gateway
    #  - linux_system_codename_xenial
    #  interfaces:
    #    eno1:
    #      role: single_dhcp
    #    eno2:
    #      role: bond0_ab_dvr_vxlan_ctl_mesh_floating
