nodes:
    cfg01.mcp11-ovs-dpdk.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_static_ctl

    cid01.mcp11-ovs-dpdk.local:
      reclass_storage_name: cicd_control_node01
      roles:
      - infra_kvm
      - cicd_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cid02.mcp11-ovs-dpdk.local:
      reclass_storage_name: cicd_control_node02
      roles:
      - infra_kvm
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    cid03.mcp11-ovs-dpdk.local:
      reclass_storage_name: cicd_control_node03
      roles:
      - infra_kvm
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_ctl

    prx01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mon01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_server_node01
      roles:
      - stacklightv2_server_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mon02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_server_node02
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mon03.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_server_node03
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mtr01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_telemetry_node01
      roles:
      - stacklight_telemetry_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mtr02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_telemetry_node02
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    mtr03.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_telemetry_node03
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    log01.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_log_node01
      roles:
      - stacklight_log_leader_v2
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    log02.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_log_node02
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl

    log03.mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: stacklight_log_node03
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp
        ens4:
          role: single_vlan_ctl
