nodes:
    ctl01.bm-mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - openstack_control_leader
      - features_designate
      - features_designate_keystone
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_vlan_ctl

    ctl02.bm-mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - openstack_control
      - features_designate
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_vlan_ctl

    ctl03.bm-mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - openstack_control
      - features_designate
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_vlan_ctl

    dbs01.bm-mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_database_node01
      roles:
      - openstack_database_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_vlan_ctl

    dbs02.bm-mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_database_node02
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_vlan_ctl

    dbs03.bm-mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_database_node03
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_vlan_ctl

    msg01.bm-mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_message_queue_node01
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_vlan_ctl

    msg02.bm-mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_message_queue_node02
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_vlan_ctl

    msg03.bm-mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_message_queue_node03
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_vlan_ctl

    prx01.bm-mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_vlan_ctl

    prx02.bm-mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_proxy_node02
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_vlan_ctl

    bmk01.bm-mcp-ocata-dvr-vxlan.local:
      reclass_storage_name: openstack_benchmark_node01
      roles:
      - openstack_benchmark
      - linux_system_codename_trusty
      interfaces:
        ens3:
          role: single_ctl