nodes:
    cfg01.released-bm-pike-ovs.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      - features_runtest_cfg
      interfaces:
        ens3:
          role: single_static_mgm
        ens4:
          role: single_static_ctl

    # Physical nodes
    kvm01.released-bm-pike-ovs.local:
      reclass_storage_name: infra_kvm_node01
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        one1:
          role: single_mgm_dhcp
        ten2:
          role: bond_ctl_lacp
        sten2:
          role: bond_ctl_lacp

    kvm02.released-bm-pike-ovs.local:
      reclass_storage_name: infra_kvm_node02
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        one1:
          role: single_mgm_dhcp
        ten2:
          role: bond_ctl_lacp
        sten2:
          role: bond_ctl_lacp

    kvm03.released-bm-pike-ovs.local:
      reclass_storage_name: infra_kvm_node03
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        one1:
          role: single_mgm_dhcp
        ten2:
          role: bond_ctl_lacp
        sten2:
          role: bond_ctl_lacp

    kvm04.released-bm-pike-ovs.local:
      reclass_storage_name: infra_kvm_node04
      roles:
      - infra_kvm_wo_gluster
      - linux_system_codename_xenial
      - salt_master_host
      interfaces:
        one1:
          role: single_mgm_dhcp
        ten2:
          role: bond_ctl_lacp
        sten2:
          role: bond_ctl_lacp

    kvm05.released-bm-pike-ovs.local:
      reclass_storage_name: infra_kvm_node05
      roles:
      - infra_kvm_wo_gluster
      - linux_system_codename_xenial
      - salt_master_host
      interfaces:
        one1:
          role: single_mgm_dhcp
        ten2:
          role: bond_ctl_lacp
        sten2:
          role: bond_ctl_lacp

    kvm06.released-bm-pike-ovs.local:
      reclass_storage_name: infra_kvm_node06
      roles:
      - infra_kvm_wo_gluster
      - linux_system_codename_xenial
      - salt_master_host
      interfaces:
        one1:
          role: single_mgm_dhcp
        ten2:
          role: bond_ctl_lacp
        sten2:
          role: bond_ctl_lacp

    osd<<count>>:
      reclass_storage_name: ceph_osd_rack01
      roles:
      - ceph_osd
      - linux_system_codename_xenial
      interfaces:
        one1:
          role: single_mgm_dhcp
        ten2:
          role: bond_ctl_lacp
        sten2:
          role: bond_ctl_lacp
#          role: bond0_ab_vlan_ceph_storage_backend

    cmp<<count>>:
      reclass_storage_name: openstack_compute_rack01
      roles:
      - openstack_compute
      - linux_system_codename_xenial
      interfaces:
        one1:
          role: single_mgm_dhcp
        ten1:
          role: bond_ctl_lacp
        ten2:
          role: bond_prv_lacp
        sten1:
          role: bond_ctl_lacp
        sten2:
          role: bond_prv_lacp

    gtw01.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        one1:
          role: single_mgm_dhcp
        ten1:
          role: bond_ctl_lacp
        ten2:
          role: bond_prv_lacp
        sten1:
          role: bond_ctl_lacp
        sten2:
          role: bond_prv_lacp

    gtw02.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_gateway_node02
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        one1:
          role: single_mgm_dhcp
        ten1:
          role: bond_ctl_lacp
        ten2:
          role: bond_prv_lacp
        sten1:
          role: bond_ctl_lacp
        sten2:
          role: bond_prv_lacp

    gtw03.released-bm-pike-ovs.local:
      reclass_storage_name: openstack_gateway_node03
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        one1:
          role: single_mgm_dhcp
        ten1:
          role: bond_ctl_lacp
        ten2:
          role: bond_prv_lacp
        sten1:
          role: bond_ctl_lacp
        sten2:
          role: bond_prv_lacp
