nodes:
    ctl01.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: openstack_control_node01
      roles:
      - openstack_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ctl02.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: openstack_control_node02
      roles:
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    ctl03.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: openstack_control_node03
      roles:
      - openstack_control
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs01.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: openstack_database_node01
      roles:
      - openstack_database_leader
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs02.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: openstack_database_node02
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    dbs03.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: openstack_database_node03
      roles:
      - openstack_database
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg01.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: openstack_message_queue_node01
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg02.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: openstack_message_queue_node02
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    msg03.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: openstack_message_queue_node03
      roles:
      - openstack_message_queue
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    prx01.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: openstack_proxy_node01
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    prx02.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: openstack_proxy_node02
      roles:
      - openstack_proxy
      - linux_system_codename_xenial
      interfaces:
        ens2:
          role: single_dhcp
        ens3:
          role: single_ctl

    cid01.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: cicd_control_node01
      roles:
      - cicd_control_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    cid02.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: cicd_control_node02
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    cid03.cookied-bm-mcp-dvr-vxlan.local:
      reclass_storage_name: cicd_control_node03
      roles:
      - cicd_control_manager
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl
