nodes:
    # Virtual Control Plane nodes

    ctl01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: kubernetes_control_node01
      roles:
      - kubernetes_control_contrail
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    ctl02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: kubernetes_control_node02
      roles:
      - kubernetes_control_contrail
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    ctl03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: kubernetes_control_node03
      roles:
      - kubernetes_control_contrail
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    # prx01.cookied-bm-mcp-ocata-contrail.local:
    #   reclass_storage_name: openstack_proxy_node01
    #   roles:
    #   - openstack_proxy
    #   - linux_system_codename_xenial
    #   interfaces:
    #     ens3:
    #       role: single_ctl

    mon01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_server_node01
      roles:
      - stacklightv2_server_leader
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    mon02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_server_node02
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    mon03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_server_node03
      roles:
      - stacklightv2_server
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    nal01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: opencontrail_analytics_node01
      roles:
      - opencontrail_analytics
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

    nal02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: opencontrail_analytics_node02
      roles:
      - opencontrail_analytics
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

    nal03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: opencontrail_analytics_node03
      roles:
      - opencontrail_analytics
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl

    ntw01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: opencontrail_control_node01
      roles:
      - opencontrail_control
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl
          single_address: 10.167.8.31

    ntw02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: opencontrail_control_node02
      roles:
      - opencontrail_control
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl
          single_address: 10.167.8.32

    ntw03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: opencontrail_control_node03
      roles:
      - opencontrail_control
      - linux_system_codename_trusty
      interfaces:
        eth1:
          role: single_ctl
          single_address: 10.167.8.33

    mtr01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_telemetry_node01
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    mtr02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_telemetry_node02
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    mtr03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_telemetry_node03
      roles:
      - stacklight_telemetry
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    log01.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_log_node01
      roles:
      - stacklight_log_leader_v2
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    log02.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_log_node02
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

    log03.cookied-bm-mcp-ocata-contrail.local:
      reclass_storage_name: stacklight_log_node03
      roles:
      - stacklight_log
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_ctl

#    bmk01.cookied-bm-mcp-ocata-contrail.local:
#      reclass_storage_name: openstack_benchmark_node01
#      roles:
#      - openstack_benchmark
#      - linux_system_codename_xenial
#      interfaces:
#        ens3:
#          role: single_ctl
