nodes:
    cfg01.cookied-bm-mcp-ovs-dpdk.local:
      reclass_storage_name: infra_config_node01
      roles:
      - infra_config
      - linux_system_codename_xenial
      interfaces:
        ens3:
          role: single_dhcp

    # Physical nodes
    kvm01.cookied-bm-mcp-ovs-dpdk.local:
      reclass_storage_name: infra_kvm_node01
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp3s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_ovs_vlan_ctl

    kvm02.cookied-bm-mcp-ovs-dpdk.local:
      reclass_storage_name: infra_kvm_node02
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp3s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_ovs_vlan_ctl

    kvm03.cookied-bm-mcp-ovs-dpdk.local:
      reclass_storage_name: infra_kvm_node03
      roles:
      - infra_kvm
      - linux_system_codename_xenial
      interfaces:
        enp3s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_ovs_vlan_ctl

    cmp01.cookied-bm-mcp-ovs-dpdk.local:
      reclass_storage_name: openstack_compute_node01
      roles:
      - openstack_compute_dpdk
      - features_lvm_backend
      - linux_system_codename_xenial
      - openstack_compute_sriov
      interfaces:
        enp3s0f0:
          role: single_mgm
          single_address: 10.167.11.105
        enp3s0f1:
          role: single_vlan_ctl
          tenant_address: 10.167.12.106
        enp5s0f0:
          role: bond2_dpdk_prv
          dpdk_pci: "0000:05:00.0"


    cmp02.cookied-bm-mcp-ovs-dpdk.local:
      reclass_storage_name: openstack_compute_node02
      roles:
      - openstack_compute_dpdk
      - features_lvm_backend
      - linux_system_codename_xenial
      - openstack_compute_sriov
      interfaces:
        enp3s0f0:
          role: single_mgm
          single_address: 10.167.11.106
        enp3s0f1:
          role: single_vlan_ctl
          tenant_address: 10.167.12.106
        enp5s0f0:
          role: bond2_dpdk_prv
          dpdk_pci: "0000:05:00.0"


    gtw01.cookied-bm-mcp-ovs-dpdk.local:
      reclass_storage_name: openstack_gateway_node01
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        enp3s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_dvr_vxlan_ctl_mesh_floating

    gtw02.cookied-bm-mcp-ovs-dpdk.local:
      reclass_storage_name: openstack_gateway_node02
      roles:
      - openstack_gateway
      - linux_system_codename_xenial
      interfaces:
        enp3s0f0:
          role: single_mgm_dhcp
        enp3s0f1:
          role: bond0_ab_dvr_vxlan_ctl_mesh_floating
